descriptions:
 resize:
  - "small image":
     src: "Images/Original/torus.gif"
     dest: "Images/Resized/"
     size: "200x700"
     aspect_ratio: true
     format:
      - jpg
      - gif

  - "big image":
     src: "Images/Original/"
     dest: "Images/Resized/"
     size: "ipad"
     format:
      - png

 crop:
  - "thumbnail":
     src: "Images/Original/"
     dest: "Images/Crop"
     from: "center"
     area: "ipod"
     prefix: "thumb-"
     format:
      - jpg
      - gif

 css_sprite:
  - "linear":
     src: "Images/Original/"
     dest: "sprite.png"
     type: "linear"
 filtering:
  - "use filters":
     src: "Images/Original/"
     dest: "Images/Filtered/"
     filters:
      - sepia
      - bw
     format:
       - gif
 rotate:
  - "rotate":
     src: "Images/Original/"
     dest: "Images/Rotated/t.pdf"
     angle: 90
     format: 
      - pdf
tasks:
  default:
   - thumbnail
   - rotate
   - big image
   - small image
   - use filters
   - linear
  custom:
   - big image
   - make b/w