descriptions:
 resize:
  - "small image":
     src: "Images/Original/"
     dest: "Images/Packed/"
     size: "100x100"
     aspect_ratio: true
     prefix: "s_i-"

  - "big image":
     src: "Images/Original/"
     dest: "Images/Horizontal/"
     size: "ipad"
     format:
      - jpg
     prefix: "b_i-"

 crop:
  - "thumbnail":
     src: "Images/Original/"
     dest: "Images/Packed/"
     from: "center"
     area: "iphone"
     prefix: "thumb-"

 css_sprite:
  - "horizontal":
     src: "Images/Horizontal"
     layout: "horizontal"
     style: "css"
     selector: "div."
     cssurl: "www.lodossteam.com"
     nocomments: true

  - "vertical":
     src: "Images/Vertical/"
     layout: "vertical"
     style: "sass"

  - "packed":
     src: "Images/Packed/"
     layout: "packed"
     style: "scss"

 filtering:
  - "black/white":
     src: "Images/Original/"
     dest: "Images/Vertical/"
     filters:
      - bw
     prefix: "bw-"

  - "sepia":
     src: "Images/Original/"
     dest: "Images/Horizontal/"
     filters:
      - sepia
     format:
      - pdf
     prefix: "sep-"

 rotate:
  - "rotate":
     src: "Images/Original/"
     dest: "Images/Horizontal"
     angle: 90
     prefix: "rotate-"
tasks:
  default:
   - small image
   - big image
   - thumbnail
   - rotate
   - black/white
   - sepia
   - horizontal
   - vertical
   - packed