descriptions:
 resize:
  - "small image":
     src: "Images/Original"
     dest: "Images/Resized/fd.jpg"
     size: "200x200"
     aspect_ratio: true
     format:
      - jpg
      - gif

  - "big image":
     src: "Images/Original/"
     dest: "Images/Resized/fd.pdf"
     size: "700x700"

 crop:
  - "thumbnail":
     src: "Images/Original/"
     dest: "Images/Crop"
     area: "200x200"
     prefix: “thumb-”
     from: "left corner"
 css_sprite:
  - "linear":
     src: "path/to/folder"
     dest: "sprite.png"
     type: "linear"
 filtering:
  - "make b/w":
     src: "path/to/folder/or/file"
     dest: "path/to/folder/or/file"
     filters:
      - bw
      - sepia
      - x-pro2
 rotate:
  - "rotate":
     src: "Images/Original/torus.gif"
     dest: "Images/Rotated/t.pdf"
     angle: 90
     format: 
      - gif
tasks:
  default:
   - rotate
   - big image
   - small image
   - make b/w
   - linear
   - thumbnail
  custom:
   - big image
   - make b/w