source 'https://rubygems.org'
gem "progressbar", "~> 0.20.0"
gem "sprite-factory"
gem 'rmagick', '2.13.2'

#        If you have problems installing RMagick" try:
#  		 sudo apt-get install libmagickcore-dev libmagickwand-dev